---
kind: pipeline
type: docker
name: vscodebuild

steps:
- name: build_vscode
  when:
    branch: vscodebuild
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/kasm-vscode-workspace
    tags: 0.0.1
    context: ""
    dockerfile: "dockerfile-kasm-vs-code"
#- name: notification
#  image: appleboy/drone-telegram
#  settings:
#    token:
#      from_secret: TELEGRAM_TOKEN
#    to:
#      from_secret: TELEGRAM_NUMBER
#    message: >
#      😄 {{repo.name}} / {{commit.branch}} - {{commit.message}}
#      {{#success build.status}}
#        ✅ succeeded  for 👷‍♂️ build {{build.number}}
#      {{else}}
#        ❌ failed for 👷‍♂️ build {{build.number}}
#      {{/success}}
#  when:
#    status:
#      - failure
#      - success
#  depends_on:
#    - build_vscode
- name: notify by EMAIL
  image: drillster/drone-email
  settings:
    host:
      from_secret: EMAIL_URL
    username:
      from_secret: EMAIL_USERNAME
    password:
      from_secret: EMAIL_PASSWD
    from: drone@mykuma.xyz
    message: >
      😄 {{repo.name}} / {{commit.branch}} - {{commit.message}}
      {{#success build.status}}
        ✅ succeeded  for 👷‍♂️ build {{build.number}}
      {{else}}
        ❌ failed for 👷‍♂️ build {{build.number}}
      {{/success}}
  when:
    status:
      - failure
      - success
  depends_on:
    - build_vscode