---
kind: pipeline
type: docker
name: desktopBuilds

steps:
- name: build_jammy_desktop
  when:
    branch: jammy_desktop
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/kasm-jammy-workspace
    tags: 0.0.1
    context: ""
    dockerfile: "dockerfile-kasm-ubuntu-jammy-desktop-kuma"
---
kind: pipeline
type: docker
name: vscodebuild
steps:
- name: build_vscode
  when:
    branch: vscodebuild
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/kasm-vscode-workspace
    tags: 0.0.1
    context: ""
    dockerfile: "dockerfile-kasm-vs-code"