---
kind: pipeline
type: docker
name: jammy_terminal

steps:
- name: build_jammy_terminal
  when:
    branch: jammy_terminal
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: DOCKERHUB_USER
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: redbeard28/kasm-terminal-workspace
    tags: 0.0.1
    context: ""
    dockerfile: "dockerfile-kasm-terminal-kuma"
- name: notify by EMAIL
  image: drillster/drone-email
  settings:
    host:
      from_secret: EMAIL_URL
    username:
      from_secret: EMAIL_USERNAME
    password:
      from_secret: EMAIL_PASSWD
    from: drone@mykuma.xyz
    message: >
      😄 {{repo.name}} / {{commit.branch}} - {{commit.message}}
      {{#success build.status}}
        ✅ succeeded  for 👷‍♂️ build {{build.number}}
      {{else}}
        ❌ failed for 👷‍♂️ build {{build.number}}
      {{/success}}
  when:
    status:
      - failure
      - success
  depends_on:
    - build_jammy_terminal